-- Create research exports storage bucket
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'research-exports',
  'research-exports',
  false,
  52428800, -- 50MB
  array[
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/markdown',
    'text/plain'
  ]
)
on conflict (id) do nothing;

-- Allow service role (API) to manage all files in research-exports bucket
-- The API verifies user authentication via Clerk before allowing uploads
create policy "Service role can manage research exports"
on storage.objects
for all
using (bucket_id = 'research-exports')
with check (bucket_id = 'research-exports');

-- Allow users to read files via signed URLs (generated by API)
create policy "Anyone can read with signed URL"
on storage.objects
for select
using (bucket_id = 'research-exports');
